### ISSUE TITLE
Adding comments to the file 

### ISSUE THREAD

**Issue by afoalb** [jasonwilliams/anki#126]
So, I have the below file to be read by anki:

```
# Deck's name

## This the the front of a card

That's the text in the front of a card

%

That's the back of a card

[#MyTag1]() [#MyTag2]()
```

How can I add comments to this file? these comments should not be interpreted by Anki. They are only for me to split the file into logical sections, because creating an entire new deck doesn't make sense.

**Comment by jasonwilliams** [comment]
Hi @afoalb is there a reason you opened then closed this issue?

**Comment by afoalb** [comment]
Hey Jason,

Totally slipped my mind that it's just a markdown file., regular   did the trick.
