### ISSUE TITLE
How do I remove various rich text html styles from the card content that vscode brings to anki

### ISSUE THREAD

**Issue by funtime1** [jasonwilliams/anki#127]
- The content transferred from vscode to anki is not plain text, such as code blocks without ``` flags.
![image](https://github.com/jasonwilliams/anki/assets/90565575/6ab3f7ea-eeb7-46b8-b058-666db5a7ec1f)

- And contains a lot of vscode styles, can I remove these styles：
![image](https://github.com/jasonwilliams/anki/assets/90565575/3b00b938-d817-40a9-90d4-962042d55dbb)

vscode dark theme:
![image](https://github.com/jasonwilliams/anki/assets/90565575/1d03318e-73c4-4e4b-af0b-a807134c7d7a)

**Comment by jasonwilliams** [comment]
@funtime1 is there a reason you closed this?
