### ISSUE TITLE
Can't send cards to Anki

### ISSUE THREAD

**Issue by Orlinky** [jasonwilliams/anki#137]
Hello,

Since 4-5 days ago I can't seem to be able to create new cards(or update old ones) using the extension, I always get this error:

`Deck not sent: request to http://127.0.0.1:8765/ failed, reason: read ECONNRESET` 

I think this started happening since I updated to the latest VS Code version(1.93) but I am not too sure.

Am I the only one having this issue?

**Comment by Orlinky** [comment]
Yeah, when I downgraded to VS Code 1.92.2, everything seems to be working again, but this is not a long term solution.

**Comment by ccvormann** [comment]
Same here. Except the reason is "socket hang up". When I invoke localhost:8765 in my browser, I get the expected response, so Anki-connect seems to work properly.

**Comment by jasonwilliams** [comment]
Thanks for raising, I have no idea what is failing here, as the extension hasn't changed in a while this will be coming from VS Code itself, I have [raised](https://github.com/microsoft/vscode/issues/228872) an issue here.

**Comment by jasonwilliams** [comment]
Ok so I've [published](https://github.com/jasonwilliams/anki/releases/tag/v1.3.5) a new release which targets 1.93+ (sorry you'll need the latest version of vs code to use it).
If people can try it out and let me know that would be great. This fix removes node-fetch and uses Electron's built-in fetch instead.

**Comment by Orlinky** [comment]
Just tried the fix and it works on my side with the latest VS Code(1.93.1).

Thank you!

**Comment by ccvormann** [comment]
I can also confirm that the fix was successful. Works fine for me now. Thanks a lot!
