### ISSUE TITLE
How can i display the blue line between the lines  please?

### ISSUE THREAD

**Issue by abedahmeduhp** [jasonwilliams/anki#15]
![unknown](https://user-images.githubusercontent.com/62298107/93352024-4e10d280-f832-11ea-8bb8-1ba164862cec.png)

**Comment by jasonwilliams** [comment]
@abedahmeduhp  im not sure what you're asking but that's specific to VScode it doesn't have anything to do with this extension. I believe that is VSCode showing you added some new content which isn't tracked
