### ISSUE TITLE
errors after vsce package command 

### ISSUE THREAD

**Issue by abedahmeduhp** [jasonwilliams/anki#17]
![image](https://user-images.githubusercontent.com/62298107/93372286-95578d00-f84b-11ea-8209-a261916bd804.png)
i want to generate the vsxi extention for developpement mode 

Executing prepublish script 'npm run vscode:prepublish'...

> anki@0.3.0 vscode:prepublish /home/abed/Bureau/anki-master
> webpack --mode development

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'yarn add -D webpack-cli')...
/bin/sh: 1: yarn: not found
undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anki@0.3.0 vscode:prepublish: `webpack --mode development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the anki@0.3.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abed/.npm/_logs/2020-09-16T17_35_51_681Z-debug.log
 ERROR  npm failed with exit code 1

**Comment by jasonwilliams** [comment]
You don't need to run vsce package to run a local version, this is for publishing.
You can just run the launch task that should be enough

**Comment by abedahmeduhp** [comment]
![image](https://user-images.githubusercontent.com/62298107/93485675-39e4d800-f8fb-11ea-9d81-58f59709d36a.png)
i run the test by the command tscrunTest.ts 
but found this error

How can i test it please

**Comment by jasonwilliams** [comment]
In VSCode go to launch, and hit play.
That’s literally it

**Comment by abedahmeduhp** [comment]
![image](https://user-images.githubusercontent.com/62298107/93492426-b4fdbc80-f902-11ea-92a2-3d8d4b64b5b3.png)
Thank you so much, how ever i found those errors 
How can i bypass them 
Thanks Jason

**Comment by abedahmeduhp** [comment]
is there any way to solve it thanks

**Comment by abedahmeduhp** [comment]
?

**Comment by jasonwilliams** [comment]
@abedahmeduhp did you sort this?
