### ISSUE TITLE
does it support latex?

### ISSUE THREAD

**Issue by trxo** [jasonwilliams/anki#18]
in markdown tag is $$....$$,but anki is [$$]...[/$$]

**Comment by jasonwilliams** [comment]
Not right now, I don’t use latex myself, PRs are welcome though

**Comment by Stedag** [comment]
I've weighed a few different approaches and here's a convenient option:

If a `use_math` setting is enabled, and a card's side contains the expressions `/.[\w\d\S]\$/`
Add "[latex]\n" and  "\n[\latex]" to the beginning and end of that side.

#### Pros:
Does not require parsing delimiters.
#### Cons:
Does not allow any markup other than latex on that side of a card.

---
This would certainly benefit those who don't want to generate separate files for Anki compatibility. Additionally, the more robust solution which involves parsing of delimiters would also need `use_math` and `math_delimiter` settings. That means half the work would already be done toward the goal of optimal math implementation.

I am getting started with https://code.visualstudio.com/api/get-started/your-first-extension to give this a try.

**Comment by janmerhar** [comment]
From what I have seen, you can use `\\( \\)` or `\\[ \\]` tags for MathJax Anki integration. Unfortunately the LaTex code is not compiled in preview, but it works in app.

**Comment by codekansas** [comment]
+1 for this, would be awesome to have a simple replacement regex for `$(.+?)$ -> \(\1\)`, `$$(.+?)$$ -> \[\1\]` when the cards are exported. I'll write a PR for this

**Comment by jasonwilliams** [comment]
Thanks @codekansas 
putting it behind a config may be useful as well, in case users want to switch this functionality off

**Comment by jasonwilliams** [comment]
Released in v1.2.0
