### ISSUE TITLE
When the image path has Chinese, the addon can't work properly

### ISSUE THREAD

**Issue by purequant** [jasonwilliams/anki#22]
This addon is very good ,but I find when the image path has Chinese, it can't work properly.

For example:

```
# mytest

## question

answer

![this work](test.png)

![this can't work](中文字符test.png)
```

and error message:

![image](https://user-images.githubusercontent.com/26440503/97863651-48b80a80-1d42-11eb-9f4b-183f25e9db15.png)

**Comment by jasonwilliams** [comment]
@purequant thanks for raising, this has been fixed in v1.0.1 which is rolling out around now
