### ISSUE TITLE
notion2anki format

### ISSUE THREAD

**Issue by ryepesg** [jasonwilliams/anki#23]
[notion2anki](https://github.com/alemayhu/notion2anki) uses toggles to separate questions from answers. I use the same pattern in VSCode using [folds](https://code.visualstudio.com/docs/editor/codebasics#_folding) to test myself from VSCode. Allowing the same format to export to Anki would be awesome, thanks!

**Comment by jasonwilliams** [comment]
@ryepesg could you explain a bit more about how this would work? I don't know very much about notion2anki

**Comment by ryepesg** [comment]
Sorry for the late reply @jasonwilliams. I have migrated my flashcards to Logseq now, so I will close this issue, thank you again!
