### ISSUE TITLE
Send to Own Deck grabs everything under title and not just the title

### ISSUE THREAD

**Issue by MicahGV** [jasonwilliams/anki#24]
So when I create a deck using the "Send To Own Deck" command the deck name basically ends up being everything under the initial "#" and I was wondering if this is expected behavior and if there is any way around it. Below are some sceenshots of what I am referring to.
![image](https://user-images.githubusercontent.com/24993737/98634128-5a705380-22e8-11eb-9811-d3af2fbc6c93.png)
![image](https://user-images.githubusercontent.com/24993737/98634175-6bb96000-22e8-11eb-9270-5f06a8036209.png)

I would assume the deck's name would just be whatever the title header has up till it reaches a new line not till it finds a new card.

If this requires some code changes that you don't think you can quickly bang out you can direct me to some files and I probably can get a PR in relatively soon as I assume this isn't a crazy bug

**Comment by jasonwilliams** [comment]
@MicahGV https://github.com/jasonwilliams/anki/blob/master/src/markdown/Serializer.ts#L75 here

**Comment by jasonwilliams** [comment]
This how now been fixed in https://github.com/jasonwilliams/anki/releases/tag/v1.0.2
