### ISSUE TITLE
Cloze not working

### ISSUE THREAD

**Issue by imalightbulb** [jasonwilliams/anki#26]
I created a markdown file with the content

`## A bit like {{c1::this}}.`

However, this error occurs when I try to send to deck.

![image](https://user-images.githubusercontent.com/66677431/99139613-4eccb600-2675-11eb-8063-b2974e616cab.png)

**Comment by jasonwilliams** [comment]
@imalightbulb what version does this happen on? Does it happen on a previous version?

**Comment by imalightbulb** [comment]
It happened on the latest version, v1.0.2
![image](https://user-images.githubusercontent.com/66677431/99144720-32477280-26a3-11eb-848e-17d14dd23b95.png)

**Comment by jasonwilliams** [comment]
@imalightbulb could you confirm it doesn’t happen on v1.0.1 ?

**Comment by imalightbulb** [comment]
Can I degrade the extension?

**Comment by jasonwilliams** [comment]
In VSCode there’s an option to install a different version yes

**Comment by imalightbulb** [comment]
Hmmm....
the same error happens in on v1.0.1 as well

**Comment by imalightbulb** [comment]
The cloze deletion doesn't work after v0.3.0

**Comment by jasonwilliams** [comment]
@imalightbulb would you be willing to work on the fix? I think the regression was introduced here https://github.com/jasonwilliams/anki/commit/9e610a14f612f5b5932cd4ff29ec4df75898ac20 

If not I’m not sure when I’ll get round to it

**Comment by imalightbulb** [comment]
Sorry but I don't know much about programming :sweat_smile:

**Comment by jasonwilliams** [comment]
No worries I’ll see what I can do

**Comment by jasonwilliams** [comment]
Fixed in https://github.com/jasonwilliams/anki/releases/tag/v1.0.3

**Comment by imalightbulb** [comment]
Thanks! :100:
