### ISSUE TITLE
Can't get it to work 

### ISSUE THREAD

**Issue by jsjoeio** [jasonwilliams/anki#3]
Hey Jason! 

First, thanks for making this! 

Second, I'm having some issues getting it to work. I wonder if you could add a "Quickstart" or "Getting Started" section to the `README.md`. 

Here's what I did:
- opened up Anki (macOS)
- installed the extension in my Foam workspace
- installed AnkiConnect
- ran command: Anki: Sync Anki 
- ~~see error: "Failed to connect to Anki: Do you have Anki running?"~~
- nothing happened
- tried the command: Anki: Send to Deck

Here is the markdown file I had open when I tried (`anki.md`):
```markdown
# Anki

## What does JS stand for?

JavaScript

## What is the best IDE/text editor for coding?

VS Code
```

I'm guessing there is something I'm missing. Any help would be appreciated! And happy to submit a PR to make it more clear in the `README.md` after. 

## additional info

Anki
Version 2.1.14 (7b93e985)
Qt 5.12.1 PyQt 5.11.3

I tried creating a new deck with called "notes" and doing the command "send to deck" 

## UPDATE

I was using an older version of Anki. I upgraded, but still nothing. Debug info from Anki below:

    
    Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
    Platform: Mac 10.14.6
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-07-27 19:23:22
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiConnect ['2055492159', 2020-07-27T18:48, 'None', '']
    Auto Markdown ['1030875226', 2019-10-12T12:30, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1030875226 2055492159
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by jsjoeio** [comment]
Okay I'm going to use this issue as a notepad as I keep trying to figure it out. So I used the "Anki: Send to Own Deck" and that got something to show up in Anki, but no cards.

**Comment by jsjoeio** [comment]
No luck. Can't figure out why Anki isn't receiving the cards.

**Comment by jasonwilliams** [comment]
Thanks for trying this out @jsjoeio 
Could you run the command with dev tools open (in VSCode, help, toggle dev tools) and see if anything shows up in there?
Usually if the deck gets created but no content it could be because another deck has those same cards somewhere, are they unique? (I fixed this but it’s not in the release)

**Comment by jasonwilliams** [comment]
Could you try deleting “notes” and running “send to deck” ?

**Comment by jasonwilliams** [comment]
I’m going to add better logging so it can be debugged a bit more easily

**Comment by jsjoeio** [comment]
I deleted "notes" and run "send to deck" with the dev tools open. Here's what showed up:

```javascript
{"action":"addNotes","version":6,"params":{"notes":
[{"deckName":"notes","modelName":"BasicWithHighlightVSCode","options":
{"allowDuplicate":false,"duplicateScope":"deck"},"fields":{"Front":"<h2 id=\"what-does-js-stand-for\">What does JS stand 
for?</h2>\n","Back":"<p>JavaScript</p>\n"},"tags":["Anki"]},
{"deckName":"notes","modelName":"BasicWithHighlightVSCode","options":
{"allowDuplicate":false,"duplicateScope":"deck"},"fields":{"Front":"<h2 id=\"what-is-the-best-idetext-editor-for-coding
\">What is the best IDE/text editor for coding?</h2>\n","Back":"<p>VS Code</p>\n"},"tags":["Anki"]},
{"deckName":"notes","modelName":"BasicWithHighlightVSCode","options":
{"allowDuplicate":false,"duplicateScope":"deck"},"fields":{"Front":"<h2 id=\"yagni\">YAGNI</h2>\n<p>Describe this 
acronym and why it&#39;s so important.</p>\n","Back":"<p>&quot;You aren&#39;t gonna need it&quot; (YAGNI) is a 
principle of extreme programming<br>(XP) that states a programmer should not add functionality until 
deemed<br>necessary.</p>\n"},"tags":["Anki"]},
{"deckName":"notes","modelName":"BasicWithHighlightVSCode","options":
{"allowDuplicate":false,"duplicateScope":"deck"},"fields":{"Front":"<h2 id=\"hello\">Hello</h2>\n","Back":"<p>please 
work</p>\n"},"tags":["Anki"]}]}}
```

And here's what I see in Anki
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/88728121-dce05900-d0e5-11ea-992a-8e5b5eaf05aa.png">

> Usually if the deck gets created but no content it could be because another deck has those same cards somewhere, are they unique? (I fixed this but it’s not in the release).

I'll try deleting everything in `anki.md` and writing new cards.

**Comment by jsjoeio** [comment]
That didn't work either. Could it be overwriting the deck and not adding the cards?

```
[Extension Host] {"action":"createDeck","version":6,"params":{"deck":"notes"}} (at t.AnkiService.<anonymous> (/Users/jprevite/.vscode-insiders/extensions/jasew.anki-0.0.1/out/extension.js:1:264997))
console.ts:137 [Extension Host] {"action":"addNotes","version":6,"params":{"notes":
[{"deckName":"notes","modelName":"BasicWithHighlightVSCode","options":
{"allowDuplicate":false,"duplicateScope":"deck"},"fields":{"Front":"<h2 id=\"why-hello-there-joe\">Why hello there 
joe</h2>\n","Back":"<p>good bye, see you later</p>\n"},"tags":["Anki"]}]}} (at t.AnkiService.<anonymous> (/Users/jprevite
/.vscode-insiders/extensions/jasew.anki-0.0.1/out/extension.js:1:264997))
```

**Comment by jasonwilliams** [comment]
I think the deck side of it is fine and the correct template isn’t there.
Can you go into your card models in Anki (Basic etc) and search for one called BasicWithHighlightVSCode ?

**Comment by jsjoeio** [comment]
I hope I'm looking in the right place. I'm not seeing one

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/88828576-4745d780-d180-11ea-86f9-83c7fd8eba5c.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/88828604-50cf3f80-d180-11ea-8e0b-8977a4bb7ccf.png">

**Comment by jasonwilliams** [comment]
Ok that was useful thanks!
So It looks like the plugin was unable to upload the correct template and that’s why the cards are failing to show up. Even though the deck exists the template doesn’t so the cards can’t be uploaded.

I don’t know why the template wasn’t installed, it’s odd. It’s supposed to keep trying if it fails (as you may not have anki running when you use the plugin, then sets a flag once it succeeds. 

the next version will have better logging and will attempt to upload it if it doesn’t exist, so hopefully we should get some useful output.

**Comment by jasonwilliams** [comment]
@jsjoeio for now you could try uninstalling the plugin. Reinstall it with dev tools open to see the console output

**Comment by jsjoeio** [comment]
Hmm...this is strange. When I install the Anki extension, these are the errors I see.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/3806031/88864057-2baaf300-d1b9-11ea-8dd1-d10ef05a0448.png">

Let me try uninstalling the Rust extension just for kicks and trying again.  No Rust errors, but nothing logged when installing the extension. I tried sending it to my decks again, but no luck either. 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/3806031/88864812-ec7da180-d1ba-11ea-85ad-7e0f163d9bd7.png">

**Comment by jasonwilliams** [comment]
@jsjoeio i've released `0.0.2` could you try starting up Anki, then opening up VSCode and downloading the new version.
You can now set `anki.log` to `info` then go to `output` and see what comes out. If you could copy and paste it here that would be useful.

It has some bug fixes in it so may work better

**Comment by jsjoeio** [comment]
It works now!!

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/89079016-6b4d1880-d33a-11ea-89d8-f50737fcede4.png">

**Comment by jasonwilliams** [comment]
Awesome!
I don’t know why it didn’t upload the template the first time, but looks like it worked this time around.
