### ISSUE TITLE
Note ids assigned to Card.id 

### ISSUE THREAD

**Issue by fletchermoore** [jasonwilliams/anki#36]
When you call Deck.pushNewCardsToAnki, you assign Node ids to the Card.id member.

When you call AnkiService.findCards, you then assign Card ids to the Card.id member.

I don't think this is causing issues in the current code but presents something of a timebomb waiting to go off as I recently discovered in my fork. I propose renaming Card.id to Card.noteId and assigning v.note to the member in AnkiService.findCards. (ref: https://github.com/FooSoft/anki-connect/blob/master/actions/cards.md)

Anki may create multiple cards for each note, depending on the note model.

**Comment by jasonwilliams** [comment]
Sounds good to me. I don’t think I’ve been on top of the card/note terminology from ankiConnect and may have mixed up the two quite a few times

**Comment by fletchermoore** [comment]
This is fixed in the pull I sent.

**Comment by jasonwilliams** [comment]
@fletchermoore I think this can be closed now as ive merged your PR
