### ISSUE TITLE
Can't update answer

### ISSUE THREAD

**Issue by hcnysa** [jasonwilliams/anki#37]
```
mac os
Version 2.1.21 (f1734a47)
Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Anki for VSCode 1.0.4
```

when i first set headline  `h1`  and answer `abc`  and send to deck  i got a card like this 
![image](https://user-images.githubusercontent.com/22735764/107118359-9309d400-68bb-11eb-9f55-7918f0a76e5d.png)

and then , i want update the answer to `123` , i change the markdown and send to deck , But it didn't seem to work，Anki not update the answer

![image](https://user-images.githubusercontent.com/22735764/107118474-3a870680-68bc-11eb-81e5-4e161b449624.png)

When I want to update an answer, I need to delete the key from anki and then resynchronize it. Is there any simple way to deal with this problem?

**Comment by jasonwilliams** [comment]
This is a duplicate issue, please see https://github.com/jasonwilliams/anki/issues/31#issuecomment-762087435
