### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by qx** [jasonwilliams/anki#43]
anki:Version ⁨2.1.38 (355e4cd5)⁩
vscod: 1.54.3 (Universal)
anki connect: AnkiConnect 0.01MB. Updated 2021-03-07.

**Comment by jasonwilliams** [comment]
@qx could you be more specific about what the issue is?

**Comment by ksrb** [comment]
![demo](https://user-images.githubusercontent.com/3750409/113297187-2acde200-92af-11eb-8652-30d4777c5a29.gif)

I can open another issue but I have a feeling that we're running into the same issue.

VS Code: 1.54.3 (system setup)
Anki: ⁨2.1.40 (cf446733)⁩
Anki Connect: 0.01MB. Updated 2021-03-07.

**Comment by jasonwilliams** [comment]
Right I see. I don’t think the explorer will reflect any changes straight away. It only fetches from Anki when you open it up. It’s not “live”.

it sounds like you went a feature request for live updates in the explorer?

**Comment by ksrb** [comment]
I can see how that GIF doesn't really show the issue 😕. 

![demo](https://user-images.githubusercontent.com/3750409/113309916-818de880-92bc-11eb-8374-1c67f8a98752.gif)

Basically nothing is getting uploaded or 'synced' and as you noticed this is on Windows OS.

**Comment by jasonwilliams** [comment]
There’s a verbose logging mode in the settings. You can turn that on and check the output

**Comment by ksrb** [comment]
Extension: v1.2.0
VS Code: 1.54.3 (system setup)
Anki: ⁨2.1.40 (cf446733)⁩
Anki Connect: 0.01MB. Updated 2021-03-07

With verbose logging in the inspector and running `Anki: Send To Deck` or `Anki: Sync Anki`

![image](https://user-images.githubusercontent.com/3750409/113335453-ce33ec80-92d9-11eb-8677-1cd2b5762241.png)

I'm not that warning actually matters though.

**Comment by jasonwilliams** [comment]
It won’t appear there, the verbose logging should appear in the output tab on the terminal. It should show requests being made to Anki.

in your settings json you need “anki.log” set to trace

**Comment by ksrb** [comment]
So I played with it a bit and managed to: 
- Fix the issue by uninstalling and installing the extension
- Duplicate the issue
- Fix the issue again by uninstalling and installing
- Failed to duplicate issue again

So after trying a bunch of things I couldn't reduplicate the issues a 3rd time 😅. 
I'm inclined to leave the issue at that for now and just suggest to others who run into a similar issue just to reinstall the extension.

If I run into the issue again hopefully, I'll have a better idea of what's causing it.

The `"anki.log": "trace"` didn't show anything of note in the Output log when I was having the issue.

**Comment by jasonwilliams** [comment]
I’ll leave this issue open for now. Feel free to let me know once you can reproduce it

**Comment by qx** [comment]
@jasonwilliams  I work on osx,  follow @ksrb 's suggestion,still not work, where can I get log for you

**Comment by ksrb** [comment]
![image](https://user-images.githubusercontent.com/3750409/114654468-14f0f180-9c9f-11eb-8985-ff4d6a0afbde.png)

Try the above, maybe you'll have better luck than me at duplicating the issue.

**Comment by DrRuhe** [comment]
I have the same problem, oddly enough, when sending to an own deck, it creates the deck in Anki, but does not populate it with the cards.
Before running anything (Settings are default, except tracing is enabled. I do not have anki sync setup (no account logged in)):
![image](https://user-images.githubusercontent.com/29500714/114706375-2aaaf900-9d29-11eb-99fe-feb2ae3f9f12.png)

After running:
![image](https://user-images.githubusercontent.com/29500714/114706537-62b23c00-9d29-11eb-89ee-09329f7a60a3.png)

The extension does not give any warning/error.

Anki Info:
    
    Anki 2.1.35 (84dcaa86) Python 3.9.2 Qt 5.15.2 PyQt 5.15.4
    Platform: Linux
    Flags: frz=False ao=True sv=1
    Add-ons, last update check: 2021-04-14 11:05:53
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AnkiConnect ['2055492159', 2021-03-07T06:17, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    2055492159
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

VSCode info:
```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.19.177-1-MANJARO
```

**Comment by jasonwilliams** [comment]
Thanks for raising. I will try to improve the tracing output to see if we can find out what’s causing it. There may also have been changes with the Anki Connect API

**Comment by jasonwilliams** [comment]
@DrRuhe could you show a screenshot of your browse tab in Anki?
Just want to know what layouts you have setup and if its installed multiple ones

**Comment by DrRuhe** [comment]
AFAIK I have no Layouts installed. However I'm new to Anki, so I don't really know what you mean. Anyways, here the screenshot:
![image](https://user-images.githubusercontent.com/29500714/114779762-cd3d9900-9d76-11eb-89cc-edc54740c633.png)

**Comment by jasonwilliams** [comment]
@DrRuhe yeah, I expected to see BasicWithHighlightVSCode in that list and it’s not there.

can you keep trace on and run “ Anki: Force Re-install” and paste the output back here. Also do another screenshot of your browse window after that.

**Comment by DrRuhe** [comment]
Here's the output after running the force reinstall. 
https://pastebin.com/m7TKZH0h

Now BasicWithHighlightVSCode seems to be there. And now it works. 
![image](https://user-images.githubusercontent.com/29500714/114783875-a719f800-9d7a-11eb-9fbe-965a3c34550e.png)

**Comment by DrRuhe** [comment]
So if anybody else has the same problem, and  BasicWithHighlightVSCode does not show up in your Browse window, try the force reinstall action. 
From my experience simply reinstalling the extension, and/or restarting anki/vscode did not help, however your mileage may vary.

**Comment by qx** [comment]
> I have the same problem, oddly enough, when sending to an own deck, it creates the deck in Anki, but does not populate it with the cards. (The "notes" deck will also be created, but not populated when running just the default Anki:Send to Deck)
> Before running anything (Settings are default, except tracing is enabled. I do not have anki sync setup (no account logged in)):
> ![image](https://user-images.githubusercontent.com/29500714/114706375-2aaaf900-9d29-11eb-99fe-feb2ae3f9f12.png)
> 
> After running:
> ![image](https://user-images.githubusercontent.com/29500714/114706537-62b23c00-9d29-11eb-89ee-09329f7a60a3.png)
> 
> The extension does not give any warning/error.
> 
> Anki Info:
> 
> ```
> Anki 2.1.35 (84dcaa86) Python 3.9.2 Qt 5.15.2 PyQt 5.15.4
> Platform: Linux
> Flags: frz=False ao=True sv=1
> Add-ons, last update check: 2021-04-14 11:05:53
> 
> 
> ===Add-ons (active)===
> (add-on provided name [Add-on folder, installed at, version, is config changed])
> AnkiConnect ['2055492159', 2021-03-07T06:17, 'None', '']
> 
> ===IDs of active AnkiWeb add-ons===
> 2055492159
> 
> ===Add-ons (inactive)===
> (add-on provided name [Add-on folder, installed at, version, is config changed])
> ```
> 
> VSCode info:
> 
> ```
> Version: 1.55.2
> Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
> Date: 2021-04-13T09:37:02.931Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Linux x64 4.19.177-1-MANJARO
> ```

```
{
  "label": "Anki for VSCode",
  "level": "trace",
  "message": "{\"action\":\"createDeck\",\"version\":6,\"params\":{\"deck\":\"MAC\"}}",
  "time": "2021-04-15T07:14:22.075Z"
}
{
  "label": "Anki for VSCode",
  "level": "trace",
  "message": "{\"action\":\"addNotes\",\"version\":6,\"params\":{\"notes\":[{\"deckName\":\"MAC\",\"modelName\":\"BasicWithHighlightVSCode\",\"options\":{\"allowDuplicate\":false,\"duplicateScope\":\"deck\"},\"fields\":{\"Front\":\"<h2 id=\\\"whats-the-markdown\\\">What&#39;s the Markdown?</h2>\\n\",\"Back\":\"<p>Markdown is a lightweight markup language with plain-text-formatting syntax.<br>Its design allows it to be converted to many output formats,<br>but the original tool by the same name only supports HTML.</p>\\n\"},\"tags\":[]},{\"deckName\":\"MAC\",\"modelName\":\"BasicWithHighlightVSCode\",\"options\":{\"allowDuplicate\":false,\"duplicateScope\":\"deck\"},\"fields\":{\"Front\":\"<h2 id=\\\"who-created-markdown\\\">Who created Markdown?</h2>\\n\",\"Back\":\"<p>John Gruber created the Markdown language in 2004 in collaboration with<br>Aaron Swartz on the syntax.</p>\\n\"},\"tags\":[]}]}}",
  "time": "2021-04-15T07:14:22.089Z"
}
{
  "label": "Anki for VSCode",
  "level": "info",
  "message": "active Editor..",
  "time": "2021-04-15T07:14:28.465Z"
}
{
  "label": "Anki for VSCode",
  "level": "trace",
  "message": "{\"action\":\"createDeck\",\"version\":6,\"params\":{\"deck\":\"notes\"}}",
  "time": "2021-04-15T07:14:28.466Z"
}
{
  "label": "Anki for VSCode",
  "level": "trace",
  "message": "{\"action\":\"addNotes\",\"version\":6,\"params\":{\"notes\":[{\"deckName\":\"notes\",\"modelName\":\"BasicWithHighlightVSCode\",\"options\":{\"allowDuplicate\":false,\"duplicateScope\":\"deck\"},\"fields\":{\"Front\":\"<h2 id=\\\"whats-the-markdown\\\">What&#39;s the Markdown?</h2>\\n\",\"Back\":\"<p>Markdown is a lightweight markup language with plain-text-formatting syntax.<br>Its design allows it to be converted to many output formats,<br>but the original tool by the same name only supports HTML.</p>\\n\"},\"tags\":[\"MAC\"]},{\"deckName\":\"notes\",\"modelName\":\"BasicWithHighlightVSCode\",\"options\":{\"allowDuplicate\":false,\"duplicateScope\":\"deck\"},\"fields\":{\"Front\":\"<h2 id=\\\"who-created-markdown\\\">Who created Markdown?</h2>\\n\",\"Back\":\"<p>John Gruber created the Markdown language in 2004 in collaboration with<br>Aaron Swartz on the syntax.</p>\\n\"},\"tags\":[\"MAC\"]}]}}",
  "time": "2021-04-15T07:14:28.489Z"
}
```
 The same with you

**Comment by qx** [comment]
It works after reinstall command
![截屏2021-04-15 下午3 28 20](https://user-images.githubusercontent.com/648406/114830846-4254b100-9dff-11eb-8b82-a9403f907ce8.png)
