### ISSUE TITLE
Send to own deck, creates a Deck but does not include the cards created.

### ISSUE THREAD

**Issue by rayanthoney** [jasonwilliams/anki#48]
### but I am unable to get the cards created to also transfer over to the created deck. As you can see by the image both decks created have the correct titles but show cards as not having been created for this deck yet.

I did note that AnkiConnect has been recently updated as of May 9th 2021.

![Desktop Screenshot 2021 05 23 - 14 14 30 67](https://user-images.githubusercontent.com/3719813/119275349-ba1db480-bbd1-11eb-977b-f619f1b42515.png)

**Comment by jasonwilliams** [comment]
@rayanthoney fan you run Anki: Force Re-install and try again?

**Comment by rayanthoney** [comment]
# Niiccee. :star2:

@jasonwilliams 
> can you run Anki: Force Re-install and try again?

Worked perfectly. I appreciate your quick response, :sparkles: That's Awesome. :sparkles:

![Desktop Screenshot 2021 05 23 - 15 33 32 43](https://user-images.githubusercontent.com/3719813/119277406-bcd1d700-bbdc-11eb-8c6b-aea32dcc9b02.png)
