### ISSUE TITLE
Only Reinstall and Syc are availabe commands.

### ISSUE THREAD

**Issue by verodhi** [jasonwilliams/anki#65]
I have been using this add-on successfully for few times. Now it has only reinstall and sync available, other commands that push to the deck are not available.

What have I done to debug:
1. Used the reinstall command.
2. Uninstall and reinstall the add-on.
3. Restart the machine and vs code.

Any suggestions on how  I can debug this will be very helpful.

System info:
OS: PopOS
VS Code version: 1.62.3

![image](https://user-images.githubusercontent.com/18559704/144078671-5b17dfbd-6ae5-432e-b3df-18a8a2398182.png)

**Comment by jasonwilliams** [comment]
The other commands only work if you're viewing a markdown file
https://github.com/jasonwilliams/anki/blob/master/package.json#L32-L41

Maybe you're viewing a file of a different type?

**Comment by verodhi** [comment]
Yes, that was the exact issue. I had *.txt extension instead of *.md.
Thank you for quick response and a great project.
