### ISSUE TITLE
Use the current directory structure as deck name

### ISSUE THREAD

**Issue by duguosheng** [jasonwilliams/anki#71]
When I write a shell or Python comment in a code block, it is incorrectly resolved to a deck name. 
So I just think about that could you please add a new option that use the current directory structure as deck name?
If the user enables this option

1. Configure the anki root directory, such as `D:/Anki`
2. The program reads the relative path from the current file to the root directory, such as `D:/Anki/Deck1/SubDeck1/note.md`
3. Generate anki deck name, `Deck1::SubDeck1`

Thanks a lot!

**Comment by jasonwilliams** [comment]
- Would you be happy with the workspace being the root directory? That would make things easier.
- Is this set as an additional command? Or a default save strategy that can be changed. (I think to begin with we may need to do a command)

**Comment by duguosheng** [comment]
> * Would you be happy with the workspace being the root directory? That would make things easier.
> * Is this set as an additional command? Or a default save strategy that can be changed. (I think to begin with we may need to do a command)

* It seems more reasonable to use workspace as the root directory.
* For my part, I prefer to use it as a save strategy that can be changed. But design it as a command is also fine  :)

**Comment by jasonwilliams** [comment]
@duguosheng wluld you be happy working on this feature? I don’t think I’ll have time to look at it anytime soon

**Comment by duguosheng** [comment]
OK, I'll try, but I don't know when it can be finished.

**Comment by jasonwilliams** [comment]
@duguosheng this has now been released https://github.com/jasonwilliams/anki/releases/tag/v1.2.6 please let me know if that version is working ok

**Comment by duguosheng** [comment]
It works, but I don't know why the option `save strategy` is at the bottom of the setting.

**Comment by jasonwilliams** [comment]
> It works, but I don't know why the option `save strategy` is at the bottom of the setting.

How/where do you mean?

**Comment by duguosheng** [comment]
I write option `save strategy` between `schema` and `defaultDeck`,

```json
"anki.api.schema": {
  // ...
},
"anki.saveStrategy": {
  // ...
},
"anki.defaultDeck": {
  // ...
},
```

But in plug-in settings, it is at the end

![image](https://user-images.githubusercontent.com/52968130/161438462-a69bac7e-febf-4e99-8ad9-5b9b7cf7f7e6.png)

**Comment by jasonwilliams** [comment]
I think its in alphabetical order
