### ISSUE TITLE
Send to DirName just creates a deck called 'deck/subdeck'

### ISSUE THREAD

**Issue by raffraffraff** [jasonwilliams/anki#80]
My directory tree is:

```
anki-decks/
└── python
    └── argparse
        └── note.md
```

If I cd to anki-decks, type `code .`, open the note and use the command 'Anki: Send to DirName deck', it just creates a new deck called 'python/argparse'. It does not create a subdeck.

Edit: I can rename the deck in Anki, replacing the `/` with `::` and it fixes the nesting. But the feature doesn't work as documented.

### OS/Software versions
OpenSUSE Tumbleweed, (KDE/Plasma) 
Anki Desktop: ⁨2.1.54, Qt6
Vs Code: 1.69

**Comment by jasonwilliams** [comment]
CC @duguosheng

**Comment by duguosheng** [comment]
I only tested this command on Windows that file path separated by `\`, this bug will be fixed soon.

**Comment by raffraffraff** [comment]
The linked PR was merged almost a month ago. When / how do new versions of the plugin get released? Since this issue appears to break DirName on _all_ non-Windows system, I think this deserves a bug fix release.

**Comment by jasonwilliams** [comment]
@raffraffraff i will try to release this week, if there isn’t a release feel free to remind me

**Comment by jasonwilliams** [comment]
1.2.7 has been released
