### ISSUE TITLE
Send to Own/DirName Deck creates deck but does not add cards

### ISSUE THREAD

**Issue by liquidsaul** [jasonwilliams/anki#83]
Title says it all.

I have the localhost instance running.

The desk is created however the actual card(s) never appear in the deck so the deck always has 0 cards and I can't add any.

Suggestions? @jasonwilliams

**Comment by liquidsaul** [comment]
Here is the markdown file I'm using to try and create cards.

# Topic1

## What's the Markdown?

Markdown is a lightweight markup language with plain-text-formatting syntax.
Its design allows it to be converted to many output formats,
but the original tool by the same name only supports HTML.

## Who created Markdown?

John Gruber created the Markdown language in 2004 in collaboration with
Aaron Swartz on the syntax.

**Comment by jasonwilliams** [comment]
CC @duguosheng

**Comment by duguosheng** [comment]
I haven't changed the code of creating card, so I don't know the reason for this...

**Comment by liquidsaul** [comment]
@jasonwilliams 

## Structure 

$  tree flashcards
flashcards
└── deck1
    └── cluster_update_maintenance.md

---

I'm guessing its a problem with my directory structure but I'm not sure what the correct setup is.

Send to deck and send to DirName Deck both don't error out and create a desk but no cards are added (even with no H1)

If I don't set H1 with "Send to own deck" the error is -> "Deck not sent: Unable to parse title!"

**Comment by liquidsaul** [comment]
Issue fixed itself after I got a new M1 Macbook and tried it there.
