### ISSUE TITLE
Remote image not work

### ISSUE THREAD

**Issue by terwer** [jasonwilliams/anki#84]
When a markdown file contains remote image, it will throw a file not found error

```
Deck not sent: ENOENT: no such file or directory, open '/Users/terwer/Documents/mydocs/src.terwer.github.io/docs/001.后端开发/002.开源框架/001.MyBatis/https:/cdn.jsdelivr.net/gh/terwer/upload/img/20220314184626.png'
```

![image](https://user-images.githubusercontent.com/3259282/191940851-462ba750-63a2-4aed-a46d-6cfb477d58e6.png)

It is better to treat remote image as a image link and add to html tags,not to check file.

**Comment by jasonwilliams** [comment]
Hey @terwer yes that’s a good point, I’m open for PRs to fix this
