### ISSUE TITLE
Support VSCodium?

### ISSUE THREAD

**Issue by GrimPixel** [jasonwilliams/anki#88]
Hi. I am currently creating a list of programs supporting Anki. If your extension is in VSCodium marketplace, I would put it on the list. How do you think?
https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/FLOSS-programs-with-Anki-support

**Comment by jasonwilliams** [comment]
I don't know what supporting VSCodium entails, do we need to do anything?

**Comment by GrimPixel** [comment]
There:
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by GrimPixel** [comment]
OK, cool. Thanks for the mentioning. It would be great if it is in the VSCodium market as well.

**Comment by FynnFreyer** [comment]
Hi @jasonwilliams, as far as I can see, the easiest way would be to add your extension to the [ovsx](https://open-vsx.org/) marketplace. You could integrate this into your [release workflow](https://github.com/jasonwilliams/anki/blob/main/.github/workflows/release.yml). To do that, you would have to

- [make an account with the eclipse foundation](https://accounts.eclipse.org/user/register) (you will need this to sign the publisher agreement for ovsx)
- sign the publisher agreement (probably a "don't sue us and don't distribute malware" kind of deal, but I haven't read it, and you need to decide if you're comfortable with that) (you will need this to create an API token)
- sign in to [open-vsx](https://open-vsx.org/) you can use your github account for this
- [create an API token](https://open-vsx.org/user-settings/tokens)
- add the token to your ci secrets, and add boilerplate to your workflow, (probably optionally) install the [ovsx package](https://www.npmjs.com/package/ovsx) with `npm i ovsx`
- lastly, add a call like `npx ovsx publish -p $newtoken` to your workflow

That should do it, I think. Would be great if you found the time, and thanks for working on this extension!

**Comment by jasonwilliams** [comment]
Sorry it took so long, how is this?
https://open-vsx.org/extension/jasew/anki

**Comment by FynnFreyer** [comment]
@jasonwilliams Looking good, thanks a lot!
